from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import asdict, dataclass
from typing import Any, Protocol

import httpx

from plugins.memory.hermes_memory.config.layer import ConfigLayer
from plugins.memory.hermes_memory.core.wikilink import LightRAGCandidate

from . import run_with_retry
from .embedding import EmbeddingBackend, build_embedding_backend


@dataclass(frozen=True, slots=True)
class LightRAGDocument:
    id: str
    text: str
    metadata: Mapping[str, Any]
    embedding: Sequence[float] | None = None


class LightRAGBackend(Protocol):
    def upsert(self, documents: Sequence[LightRAGDocument]) -> Mapping[str, Any]:
        ...

    def query_related(self, text: str, *, top_k: int) -> Sequence[LightRAGCandidate]:
        ...

    def delete(self, document_ids: Sequence[str]) -> Mapping[str, Any]:
        ...


class LightRAGHTTPBackend:
    def __init__(
        self,
        *,
        config: ConfigLayer,
        embedding_backend: EmbeddingBackend | None = None,
        client: httpx.Client | None = None,
    ) -> None:
        self._config = config
        self._embedding_backend = embedding_backend or build_embedding_backend(config)
        base_url = config.settings.lightrag.endpoint or config.settings.lightrag.base_url
        self._client = client or httpx.Client(base_url=base_url, timeout=config.settings.lightrag.timeout_seconds)

    def upsert(self, documents: Sequence[LightRAGDocument]) -> Mapping[str, Any]:
        path = self._require_path(self._config.settings.lightrag.upsert_path, operation='upsert')
        if path.rstrip('/') == '/documents/texts':
            payload = self._official_upsert_payload(documents)
        else:
            payload = self._legacy_upsert_payload(documents)
        return run_with_retry(lambda: self._request('POST', path, payload))

    def query_related(self, text: str, *, top_k: int) -> Sequence[LightRAGCandidate]:
        query_path = self._config.settings.lightrag.query_path
        payload = {
            'query': text,
            'top_k': top_k,
            'include_references': True,
            'include_chunk_content': False,
            'only_need_context': True,
            'stream': False,
        }
        response = run_with_retry(lambda: self._request('POST', query_path, payload))
        raw_results = response.get('results')
        if isinstance(raw_results, list):
            return [_to_candidate(item, index=index) for index, item in enumerate(raw_results)]
        raw_references = response.get('references')
        if isinstance(raw_references, list):
            return [_to_reference_candidate(item, index=index) for index, item in enumerate(raw_references)]
        return []

    def delete(self, document_ids: Sequence[str]) -> Mapping[str, Any]:
        path = self._require_path(self._config.settings.lightrag.delete_path, operation='delete')
        payload = {'doc_ids': list(document_ids)} if path.rstrip('/') == '/documents/delete_document' else {'ids': list(document_ids)}
        return run_with_retry(lambda: self._request('DELETE', path, payload))

    def _legacy_upsert_payload(self, documents: Sequence[LightRAGDocument]) -> Mapping[str, Any]:
        embeddings = [
            list(document.embedding) if document.embedding is not None else vector
            for document, vector in zip(
                documents,
                self._embedding_backend.embed_documents([document.text for document in documents]),
                strict=True,
            )
        ]
        return {
            'documents': [asdict(document) for document in documents],
            'embeddings': embeddings,
        }

    def _official_upsert_payload(self, documents: Sequence[LightRAGDocument]) -> Mapping[str, Any]:
        # NOTE: live /openapi.json was unavailable during Phase 5, so this follows
        # the official LightRAG HKU PyPI HTTP interface (/documents/texts).
        # Precomputed embeddings are generated by the interpreter pipeline and kept
        # in document metadata for local validation, but the published HTTP request
        # shape only accepts texts/file_sources.
        file_sources: list[str] = []
        for document in documents:
            file_source = document.metadata.get('file_source') or document.metadata.get('path') or document.id
            file_sources.append(str(file_source))
        return {
            'texts': [document.text for document in documents],
            'file_sources': file_sources,
        }

    def _request(self, method: str, path: str, payload: Mapping[str, Any]) -> Mapping[str, Any]:
        response = self._client.request(method, path, json=payload)
        response.raise_for_status()
        data = response.json()
        if not isinstance(data, dict):
            raise ValueError('LightRAG response must deserialize to an object')
        return data

    @staticmethod
    def _require_path(path: str | None, *, operation: str) -> str:
        if path is None or not path.strip():
            raise ValueError(f'LightRAG {operation} path is not configured.')
        return path


def _to_candidate(raw: object, *, index: int) -> LightRAGCandidate:
    if not isinstance(raw, Mapping):
        raise ValueError('LightRAG result items must be objects')
    title = raw.get('title', '')
    path = raw.get('path', '')
    score = raw.get('score', max(0.0, 1.0 - (index * 0.01)))
    note_type = raw.get('type', 'knowledge')
    if not isinstance(title, str) or not isinstance(path, str) or not isinstance(note_type, str):
        raise ValueError('LightRAG result title/path/type must be strings')
    if isinstance(score, bool) or not isinstance(score, int | float):
        raise ValueError('LightRAG result score must be numeric')
    return LightRAGCandidate(title=title, path=path, score=float(score), type=note_type)


def _to_reference_candidate(raw: object, *, index: int) -> LightRAGCandidate:
    if not isinstance(raw, Mapping):
        raise ValueError('LightRAG reference items must be objects')
    raw_path = raw.get('file_path', '')
    if not isinstance(raw_path, str):
        raise ValueError('LightRAG reference file_path must be a string')
    path = raw_path
    title = raw_path.rsplit('/', 1)[-1].removesuffix('.md') if raw_path else ''
    raw_reference_id = raw.get('reference_id', '')
    if title == '' and isinstance(raw_reference_id, str):
        title = raw_reference_id
    # Official PyPI query docs expose references without score/type fields.
    # Until live OpenAPI is measured, preserve usefulness for callers by
    # assigning a stable rank score and falling back to knowledge type.
    return LightRAGCandidate(title=title, path=path, score=max(0.0, 1.0 - (index * 0.01)), type='knowledge')
